frontend_homepage:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/Main:index" }

frontend_search:
    path:     /search
    defaults: { _controller: "SiteMainBundle:Frontend/Search:index" }

frontend_news_young:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/news-young.yml"
    prefix: /page/molodiezhnaia-orghanizatsiia-iedinaia-alaniia/novosti-1

frontend_news_stock:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/news-stock.yml"
    prefix: /page/molodiezhnaia-orghanizatsiia-iedinaia-alaniia/aktsii

frontend_page:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/page.yml"
    prefix:   /page

frontend_news:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/news.yml"
    prefix: /novosti

frontend_quote:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/quote.yml"
    prefix: /tsitaty

frontend_news_paper:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/news_paper.yml"
    prefix: /gaziety

frontend_photo:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/photo.yml"
    prefix: /photo

frontend_video:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/video.yml"
    prefix: /video